use-sort:
    sort-type: alph
    sort-direction: asc

header: |
    /**
     * Geolocation Ipstack (http://mateuszsitek.com/projects/geolocation-ipstack)
     *
     * @copyright Copyright (c) 2017-2018 DIGITAL WOLVES LTD (http://digitalwolves.ltd) All rights reserved.
     * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3-Clause
     */
